- hosts: localhost

  tasks:
  - name: install openjdk-8-jdk 
    apt:
      name: openjdk-8-jdk
    become: yes

  - name: install standard Scala applications 
    shell: |
      curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs 
      chmod +x cs
      ./cs setup -y

  - name: install intellij-idea
    become: yes
    shell: snap install intellij-idea-community --classic 
