- hosts: localhost

  tasks:
  - name: install qemu-kvm
    apt:
      name: qemu-kvm
    become: yes

  - name: install libvirt-daemon-system
    apt:
      name: libvirt-daemon-system
    become: yes

  - name: install libvirt-clients
    apt:
      name: libvirt-clients
    become: yes

  - name: install bridge-utils
    apt:
      name: bridge-utils
    become: yes

  - name: install virt-manager
    apt:
      name: virt-manager 
    become: yes

  - name: install vagrant
    apt:
      name: vagrant 
    become: yes

  - name: install vagrant-libvirt
    apt:
      name: vagrant-libvirt 
    become: yes
