- hosts: localhost

  tasks:
  - name: install libsecret-common
    apt:
      name: libsecret-common
    become: yes

  - name: install libsecret-1-0
    apt:
      name: libsecret-1-0
    become: yes

  - name: install libxss1
    apt:
      name: libxss1
    become: yes

  - name: add repo for vscode 
    shell: |
      curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
      install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
      echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list
      apt update
    become: yes

  - name: install code
    apt:
      name: code 
    become: yes
